/*
 * NewJDialog.java
 *
 * Created on 10 décembre 2008, 11:45
 */

package biblio;

import java.util.*;
/**
 *
 * @author  mailleta
 */
public class VueLecteurGUI extends javax.swing.JDialog {
    
     private Lecteur lect;

//*************************
//     Constructeur
//*************************
 public VueLecteur (Lecteur lect) {
   // Liaison à l'objet Lecteur
   this.lierLecteur(lect);

   // pour MVC :: la vue s'ajoute comme observateur de l'objet lect
   lect.addObserver(this);

   this.afficherTout();
 } // Fin Constructeur

// ********************************
//      Méthodes publiques
// ********************************
 public void update(Observable obs, Object o) {
   // maj de la vue
   this.afficherTout();
 }  // Fin upDate

 //********************************
 public void elimineObserveur() {
   lect.deleteObserver(this);
 } // Fin elimineObserveur

 // *******************************
//       Méthodes privées
// ********************************
 private void afficherTout()  {
   System.out.println();
   System.out.println("                 --------------------------------- ");
   System.out.println("                 -            LECTEUR            - ");
   System.out.println("                 --------------------------------- ");
   System.out.println("                 - Numero  = " + lect.numero() );
   System.out.println("                 - Nom  = " + lect.nom() );
   System.out.println("                 - Libellé  = " + lect.prenom() );
   System.out.println("                 - Adresse = " + lect.adresse() );
   System.out.println("                 - Age = " + lect.age());
   System.out.println("                 --------------------------------- ");
} // Fin afficherTout

//**********************************
private void lierLecteur(Lecteur lec) {
      lect = lec;
}
    /** Creates new form NewJDialog */
    public VueLecteurGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        nom_label = new javax.swing.JLabel();
        prenom_label = new javax.swing.JLabel();
        adresse_label = new javax.swing.JLabel();
        age_label = new javax.swing.JLabel();
        prenom_textfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        adresse_textarea = new javax.swing.JTextArea();
        nom_textfield = new javax.swing.JTextField();
        age_spin = new javax.swing.JSpinner();
        terminer_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lecteur");

        nom_label.setText("Nom :");

        prenom_label.setText("Prenom :");

        adresse_label.setText("Adresse :");

        age_label.setText("Age :");

        adresse_textarea.setColumns(20);
        adresse_textarea.setRows(5);
        jScrollPane1.setViewportView(adresse_textarea);

        terminer_button.setText("Terminer");
        terminer_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                terminer_buttonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom_label)
                    .addComponent(prenom_label)
                    .addComponent(adresse_label)
                    .addComponent(age_label))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prenom_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addComponent(nom_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(age_spin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(terminer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_label)
                    .addComponent(nom_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
 