package biblio;

/*
 * CtrNouvLecteurGUI.java
 *
 * Created on 10 décembre 2008, 10:55
 */

import java.util.*;

/**
 *
 * @author  mailleta
 */
public class CtrNouvLecteurGUI extends javax.swing.JDialog {
    
    private Bibliotheque biblio;

    /** Creates new form CtrNouvLecteurGUI */
    public CtrNouvLecteurGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nom_label = new javax.swing.JLabel();
        prenom_label = new javax.swing.JLabel();
        adresse_label = new javax.swing.JLabel();
        age_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajout d'un nouveau lecteur");

        nom_label.setText("Nom :");

        prenom_label.setText("Prenom :");

        adresse_label.setText("Adresse :");

        age_label.setText("Age :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(age_label)
                    .addComponent(adresse_label)
                    .addComponent(prenom_label)
                    .addComponent(nom_label))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(nom_label)
                .addGap(27, 27, 27)
                .addComponent(prenom_label)
                .addGap(43, 43, 43)
                .addComponent(adresse_label)
                .addGap(47, 47, 47)
                .addComponent(age_label)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CtrNouvLecteurGUI dialog = new CtrNouvLecteurGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresse_label;
    private javax.swing.JLabel age_label;
    private javax.swing.JLabel nom_label;
    private javax.swing.JLabel prenom_label;
    // End of variables declaration//GEN-END:variables
    
}
