/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VueOuvrageGUI.java
 *
 * Created on 12 déc. 2008, 11:54:28
 */

package biblio;

import java.util.*;
/**
 *
 * @author ksz
 */
public class VueOuvrageGUI extends javax.swing.JDialog implements Observer {

    private Ouvrage ouvrage;
    private java.awt.Frame parent_frame;
    
    /** Creates new form VueOuvrageGUI */
    public VueOuvrageGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parent_frame = parent;
        initComponents();
        this.setLocationRelativeTo(this.getParent());
    }

    public void menuPrincipal(Ouvrage ouv) {
        ouvrage = ouv;
        ouvrage.addObserver(this);
        this.afficherTout();
        this.setVisible(true);
    }

     //********************************
     public void elimineObserveur() {
        ouvrage.deleteObserver(this);
     } // Fin elimineObserveur

    private void afficherTout()  {
        isbn_textfield.setText(ouvrage.isbn());
        titre_textfield.setText(ouvrage.titre());
        auteur_textfield.setText(ouvrage.auteur());
        editeur_textfield.setText(ouvrage.editeur());

        java.text.DateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");
        java.util.Date dateDate = ouvrage.dateEdition().getTime();
        String dateString = dateFormat.format(dateDate);
        date_textfield.setText(dateString);

        nbexemp_textfield.setText(Integer.toString(ouvrage.nbExemplaires()));
        

       this.afficherListeExemplaires();

    }

    private void afficherListeExemplaires() {
      Enumeration enumEx = ouvrage.enumExemplaires();
      /**
      if  (enumEx.hasMoreElements()) {

          while (enumEx.hasMoreElements()) {
              Exemplaire exemp = (Exemplaire) enumEx.nextElement();
              try {
                 exemplaires_table.getModel().setValueAt(Integer.toString(exemp.numero()), i, 0);
                 exemplaires_table.getModel().setValueAt(exemp.libStatut(), i, 1);
                 exemplaires_table.addRowSelectionInterval(i, i+1);
              } catch(Exception e) {
                  javax.swing.JOptionPane.showMessageDialog(null, "mon code sux");
              }
              i = i+1;
          }
      }
       * */

      javax.swing.table.DefaultTableModel dtm = new javax.swing.table.DefaultTableModel();
      Vector<Vector<Object>> data = new Vector<Vector<Object>>();
      data.clear();
      Vector<String> column = new Vector<String>();
      column.clear();
      column.add("Numéro");
      column.add("Statut");
      if  (enumEx.hasMoreElements()) {
          while (enumEx.hasMoreElements()) {
              Vector<Object> data_line = new Vector<Object>();
              Exemplaire exemp = (Exemplaire) enumEx.nextElement();
              data_line.add(Integer.toString(exemp.numero()));
              data_line.add(exemp.libStatut());
              data.add(data_line);
          }
      }
      
      dtm.setDataVector(data, column);
      exemplaires_table.setModel(dtm);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        terminer_button = new javax.swing.JButton();
        auteur_label = new javax.swing.JLabel();
        titre_label = new javax.swing.JLabel();
        editeur_label = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        auteur_textfield = new javax.swing.JTextField();
        titre_textfield = new javax.swing.JTextField();
        editeur_textfield = new javax.swing.JTextField();
        date_textfield = new javax.swing.JTextField();
        isbn_label = new javax.swing.JLabel();
        isbn_textfield = new javax.swing.JTextField();
        nbexemp_label = new javax.swing.JLabel();
        nbexemp_textfield = new javax.swing.JTextField();
        exemplaires_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        exemplaires_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajout d'un ouvrage");
        setResizable(false);

        terminer_button.setText("Terminer");
        terminer_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                terminer_buttonMousePressed(evt);
            }
        });

        auteur_label.setText("Auteur :");

        titre_label.setText("Titre :");

        editeur_label.setText("Editeur :");

        date_label.setText("Date edition :");

        auteur_textfield.setEditable(false);

        titre_textfield.setEditable(false);

        editeur_textfield.setEditable(false);

        date_textfield.setEditable(false);
        date_textfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        isbn_label.setText("Numero ISBN :");

        isbn_textfield.setEditable(false);

        nbexemp_label.setText("Nombre d'exemplaires :");

        nbexemp_textfield.setEditable(false);
        nbexemp_textfield.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        exemplaires_label.setText("Exemplaires :");

        exemplaires_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Statut"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exemplaires_table.setCellSelectionEnabled(true);
        exemplaires_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(exemplaires_table);
        exemplaires_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        exemplaires_table.getColumnModel().getColumn(0).setResizable(false);
        exemplaires_table.getColumnModel().getColumn(1).setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(auteur_label, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(titre_label, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(isbn_label, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exemplaires_label, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(editeur_label, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(date_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nbexemp_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addComponent(editeur_textfield)
                    .addComponent(auteur_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(titre_textfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(isbn_textfield, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbexemp_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(terminer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbn_label)
                    .addComponent(isbn_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titre_label)
                    .addComponent(titre_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(auteur_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auteur_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editeur_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editeur_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbexemp_label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbexemp_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exemplaires_label)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(terminer_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terminer_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terminer_buttonMousePressed
        // TODO add your handling code here:
        // Vérification la non existence de l'ouvrage / ISBN
        this.dispose();
}//GEN-LAST:event_terminer_buttonMousePressed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VueOuvrageGUI dialog = new VueOuvrageGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel auteur_label;
    private javax.swing.JTextField auteur_textfield;
    private javax.swing.JLabel date_label;
    private javax.swing.JTextField date_textfield;
    private javax.swing.JLabel editeur_label;
    private javax.swing.JTextField editeur_textfield;
    private javax.swing.JLabel exemplaires_label;
    private javax.swing.JTable exemplaires_table;
    private javax.swing.JLabel isbn_label;
    private javax.swing.JTextField isbn_textfield;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nbexemp_label;
    private javax.swing.JTextField nbexemp_textfield;
    private javax.swing.JButton terminer_button;
    private javax.swing.JLabel titre_label;
    private javax.swing.JTextField titre_textfield;
    // End of variables declaration//GEN-END:variables

     public void update(Observable obs, Object o) {
       // maj de la vue
       this.afficherTout();
     }  // Fin upDate

}
