package biblio;
import java.awt.Color;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CtrNouvParutionGUI.java
 *
 * Created on 15 déc. 2008, 13:16:14
 */

/**
 *
 * @author ardaudg
 */
public class CtrNouvParutionGUI extends javax.swing.JDialog {

private Bibliotheque biblio;
private java.awt.Frame parent_frame;

    /** Creates new form CtrNouvParutionGUI */
    public CtrNouvParutionGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parent_frame = parent;
        initComponents();
        this.setLocationRelativeTo(this.getParent());
    }

    public void menuPrincipal(Bibliotheque bib) {
        biblio = bib;
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        issn_label = new javax.swing.JLabel();
        annuler_button = new javax.swing.JButton();
        valider_button = new javax.swing.JButton();
        issn_textfield = new javax.swing.JTextField();
        rechercher_button = new javax.swing.JButton();
        nom_periodique_label = new javax.swing.JLabel();
        nom_periodique_textfield = new javax.swing.JTextField();
        id_parution_label = new javax.swing.JLabel();
        id_parution_textfield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mot_cle_jlist = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        auteur_jlist = new javax.swing.JList();
        mots_cles_label = new javax.swing.JLabel();
        auteur_label = new javax.swing.JLabel();
        ajouter_motcle_button = new javax.swing.JButton();
        ajouter_auteur_button = new javax.swing.JButton();
        article_label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        article_jtable = new javax.swing.JTable();
        ajouter_article_button = new javax.swing.JButton();
        supprimer_article_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajout d'une parution");
        setResizable(false);

        issn_label.setText("Numero ISSN :");

        annuler_button.setText("Annuler");
        annuler_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                annuler_buttonMousePressed(evt);
            }
        });

        valider_button.setText("Valider");
        valider_button.setEnabled(false);
        valider_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                valider_buttonMousePressed(evt);
            }
        });

        rechercher_button.setText("Rechercher");
        rechercher_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rechercher_buttonMousePressed(evt);
            }
        });

        nom_periodique_label.setText("Nom du périodique:");

        nom_periodique_textfield.setBackground(new java.awt.Color(254, 254, 254));
        nom_periodique_textfield.setEditable(false);
        nom_periodique_textfield.setForeground(new java.awt.Color(254, 254, 254));
        nom_periodique_textfield.setText("(recherchez un ISSN)");
        nom_periodique_textfield.setToolTipText("Nom du périodique ayant l'ISSN spécifié.");
        nom_periodique_textfield.setEnabled(false);

        id_parution_label.setText("Identifiant de parution:");

        id_parution_textfield.setToolTipText("Entrez ici l'identifiant de parution du périodique spécifié.");
        id_parution_textfield.setEnabled(false);
        id_parution_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_parution_textfieldActionPerformed(evt);
            }
        });

        mot_cle_jlist.setEnabled(false);
        jScrollPane1.setViewportView(mot_cle_jlist);

        auteur_jlist.setEnabled(false);
        auteur_jlist.setFocusable(false);
        jScrollPane2.setViewportView(auteur_jlist);

        mots_cles_label.setText("Mots clés:");

        auteur_label.setText("Auteurs:");

        ajouter_motcle_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/plus_icon.gif"))); // NOI18N
        ajouter_motcle_button.setText("Ajouter");
        ajouter_motcle_button.setEnabled(false);
        ajouter_motcle_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajouter_motcle_buttonMousePressed(evt);
            }
        });

        ajouter_auteur_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/plus_icon.gif"))); // NOI18N
        ajouter_auteur_button.setText("Ajouter");
        ajouter_auteur_button.setEnabled(false);
        ajouter_auteur_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajouter_auteur_buttonMousePressed(evt);
            }
        });

        article_label.setText("Article");

        article_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"OpenBSD", "14"},
                {"Rootkit", "28"}
            },
            new String [] {
                "Titre", "Page"
            }
        ));
        jScrollPane3.setViewportView(article_jtable);

        ajouter_article_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/plus_icon.gif"))); // NOI18N
        ajouter_article_button.setText("Ajouter");
        ajouter_article_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajouter_article_buttonMousePressed(evt);
            }
        });

        supprimer_article_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblio/minus_icon.png"))); // NOI18N
        supprimer_article_button.setText("Supprimer");
        supprimer_article_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                supprimer_article_buttonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(issn_label, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(nom_periodique_label, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(id_parution_label, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(id_parution_textfield)
                                    .addComponent(nom_periodique_textfield)
                                    .addComponent(issn_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rechercher_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(annuler_button, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(valider_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(supprimer_article_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ajouter_article_button))
                            .addComponent(article_label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ajouter_auteur_button)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(auteur_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ajouter_motcle_button, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mots_cles_label))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issn_label)
                    .addComponent(rechercher_button)
                    .addComponent(issn_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nom_periodique_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_periodique_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_parution_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_parution_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mots_cles_label)
                        .addComponent(article_label))
                    .addComponent(auteur_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ajouter_motcle_button))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, 0, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ajouter_article_button)
                                .addComponent(supprimer_article_button))
                            .addComponent(ajouter_auteur_button))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annuler_button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annuler_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annuler_buttonMousePressed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_annuler_buttonMousePressed

    private void valider_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_valider_buttonMousePressed
        // TODO add your handling code here:

}//GEN-LAST:event_valider_buttonMousePressed

    private void rechercher_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercher_buttonMousePressed
        // TODO add your handling code here:
        String issn = issn_textfield.getText();
        Periodique period = null;//biblio.unPeriodique(issn);
        if (period == null) {
            nom_periodique_textfield.setDisabledTextColor(Color.red);
            nom_periodique_textfield.setText("L'ISSN spécifié n'existe pas.");
        } else {
            nom_periodique_textfield.setText("Le monde");
        }

}//GEN-LAST:event_rechercher_buttonMousePressed

    private void id_parution_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_parution_textfieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_id_parution_textfieldActionPerformed

    private void ajouter_motcle_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter_motcle_buttonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter_motcle_buttonMousePressed

    private void ajouter_auteur_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter_auteur_buttonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter_auteur_buttonMousePressed

    private void ajouter_article_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouter_article_buttonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajouter_article_buttonMousePressed

    private void supprimer_article_buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimer_article_buttonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_supprimer_article_buttonMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CtrNouvParutionGUI dialog = new CtrNouvParutionGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter_article_button;
    private javax.swing.JButton ajouter_auteur_button;
    private javax.swing.JButton ajouter_motcle_button;
    private javax.swing.JButton annuler_button;
    private javax.swing.JTable article_jtable;
    private javax.swing.JLabel article_label;
    private javax.swing.JList auteur_jlist;
    private javax.swing.JLabel auteur_label;
    private javax.swing.JLabel id_parution_label;
    private javax.swing.JTextField id_parution_textfield;
    private javax.swing.JLabel issn_label;
    private javax.swing.JTextField issn_textfield;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList mot_cle_jlist;
    private javax.swing.JLabel mots_cles_label;
    private javax.swing.JLabel nom_periodique_label;
    private javax.swing.JTextField nom_periodique_textfield;
    private javax.swing.JButton rechercher_button;
    private javax.swing.JButton supprimer_article_button;
    private javax.swing.JButton valider_button;
    // End of variables declaration//GEN-END:variables

}
